//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace books.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        public int id { get; set; }
        [DisplayName("Usuário")]
        [Required(ErrorMessage ="This field is required")]
        public string name { get; set; }
        [DataType(DataType.Password)]
        [DisplayName("Senha")]
        [Required(ErrorMessage = "This field is required")]
        public string password { get; set; }

        public string loginError { get; set; }
    }
}
